const moo = require('moo')
 
module.exports = lexer = moo.compile({
    keyword: ['webapp', 'page', 'import', 'head', 'body', 'title', 'stylesheet', 'script', 'header', 'content', 'footer', 'list', 'image', 'dyn', 'block', 'if', 'or', 'in', 'loop', 'loopback', 'count', 'final', 'return', 'switch'],
    identifier: /[a-zA-Z][a-zA-Z_0-9]*/,
    lparen:  '(',
    rparen:  ')',
    lbrace:  '{',
    rbrace:  '}',
    lbracket:  '[',
    rbracket:  ']',
    gt: '>>',
    lt: '<<',
    equalto: '==',
    notequal: '!=',
    incr: '++',
    decr: '--',
    divoff: '/=',
    mulon: '*=',
    addon: '+=',
    suboff: '-=',
    and: '&&',
    or: '||',
    not: '!',
    ltag: '<',
    rtag: '>',
    mod: '%',
    div: '/',
    mul: '*',
    add: '+',
    sub: '-',
    godo: '=>',
    assign: '=',
    comma: ',',
    wspace:  /[ \t]+/,
    number:  /(?:0|[1-9][0-9_]*)/,
    string:  /"(?:\\["\\]|[^\n"\\])*"/,
    newline: { match: /\r\n/, lineBreaks: true },
    comment: /\/\/.*?$/,
});